### ISSUE TITLE
zizmor reports "invalid GitHub Actions workflow" for a workflow github accepts (but does not run)

### ISSUE THREAD

**Issue by jepler** [woodruffw/zizmor#109]
Hi! As I investigated this, I am starting to think this is something weird in our Actions setup, because the related workflow has never run according to https://github.com/adafruit/circuitpython/actions/workflows/run-tests.yml

However, I still wanted to report that zizmor rejects this as an invalid actions file, despite the fact that GH accepts it (and never runs it since it is only 'on workflow_call' and we don't actually call it)

Steps to reproduce:
 1. Download a raw copy of https://github.com/adafruit/circuitpython/blob/main/.github/workflows/run-tests.yml
 2. run zizmor on it

```
$ zizmor --version
zizmor 0.1.5
$ zizmor run-tests.yml 
Error: invalid GitHub Actions workflow: "run-tests.yml"

Caused by:
    jobs: data did not match any variant of untagged enum Job at line 11 column 3
```

**Comment by woodruffw** [comment]
Thanks for the report @jepler! There's a good chance that this is a bug in our modeling, similar to https://github.com/woodruffw/github-actions-models/pull/8 and https://github.com/woodruffw/github-actions-models/pull/9. I'll triage this now.

**Comment by woodruffw** [comment]
Yep, I've root-caused this: your workflow has an `env:` member like this:

```yaml
TEST_all:
```

i.e. where the key is `null`. This is perfectly valid, but we don't support it yet because I hadn't seen it before. Should be a simple fix!

**Comment by woodruffw** [comment]
#112 should fix this!

**Comment by jepler** [comment]
Thank you!
