### ISSUE TITLE
Generalize matrix handling

### ISSUE THREAD

**Issue by woodruffw** [woodruffw/zizmor#114]
#113 and #22 reveal the limitations of our current (primitive) approach to processing matrices and matrix expressions. We need a more general approach.

Some rough ideas:

1. We probably need a `models::Matrix` API similar to the ones for `Job`, `Step`, etc. to provide convenience APIs.
2. We probably need a one-shot API for "all possible expansions of this `matrix.foobar` expression". This could probably be done with [serde_json_path](https://docs.rs/serde_json_path/latest/serde_json_path/).

Needs further design thought; feedback & thoughts welcome!

**Comment by ubiratansoares** [comment]
@woodruffw I have a proposal here https://github.com/woodruffw/zizmor/pull/231, let me know your thoughts 🙂
