### ISSUE TITLE
New audit: un-pinned action audit

### ISSUE THREAD

**Issue by funnelfiasco** [woodruffw/zizmor#141]
### Pre-submission checks

- [X] I am **not** a bug (crash, false positive/negative, etc). These must be filed via the bug report template.
- [X] I have looked through the open issues for a duplicate request.

### What's the problem this feature will solve?

GitHub Actions may become compromised due to account takeover, social engineering, etc. It's a good idea to pin actions to known-good versions so that a workflow isn't silently compromised by a change in an action.

### Describe the solution you'd like

An audit that checks for actions without a version. For example, it would flag `actions/checkout`. For extra security, it could require a commit ID, since tags could be overwritten by an attacker.

**Comment by woodruffw** [comment]
Big +1 to this audit idea! This is mentioned in the audit roadmap (#1), but it's good to have this issue as an independent breakout for it as well 🙂

**Comment by woodruffw** [comment]
I'm going to take a stab at this later today.
