### ISSUE TITLE
Feature: "(0 ignored)" seems superfluous

### ISSUE THREAD

**Issue by nedbat** [woodruffw/zizmor#147]
### Pre-submission checks

- [X] I am **not** a bug (crash, false positive/negative, etc). These must be filed via the bug report template.
- [X] I have looked through the open issues for a duplicate request.

### What's the problem this feature will solve?

I get results like:
> No findings to report. Good job! (0 ignored)

I think the message would be a clearer celebration of success as just:
> No findings to report. Good job!

### Describe the solution you'd like

If there are ignored findings, of course, include the ignored count. But "0 ignored" doesn't seem like something to mention.

**Comment by woodruffw** [comment]
Agreed, that's completely superfluous. I'll look at removing it!

**Comment by woodruffw** [comment]
#148 will address this.

**Comment by nedbat** [comment]
Thanks, but I installed 0.3.1 and still see the "(0 ignored)" messages.

**Comment by woodruffw** [comment]
🤦 I removed the wrong `(0 ignored)` message. Sorry about that, I'll also remove that one when it's superfluous.
