### ISSUE TITLE
New audit: `ACTIONS_ALLOW_UNSECURE_COMMANDS`

### ISSUE THREAD

**Issue by woodruffw** [woodruffw/zizmor#171]
Setting this anywhere in the environment re-enables GHA's old `::set-env` command, which makes code injection via the environment much easier.

Ref: https://semgrep.dev/r?q=yaml.github-actions.security.allowed-unsecure-commands.allowed-unsecure-commands

**Comment by ubiratansoares** [comment]
Hey @woodruffw ! I'd love to contributing with a new audit, this looks like an easy one to get started! 😄

Ooc, which criticality would you assign to this finding?

**Comment by woodruffw** [comment]
Thanks @ubiratansoares! It's all yours to work on.

I think this should be "high" severity: it opens up a well-known security hole that's been disabled by default for years.
