### ISSUE TITLE
Plain output: render confidence

### ISSUE THREAD

**Issue by woodruffw** [woodruffw/zizmor#19]
Follow-on to #18: we render the severity, but not the confidence currently. Need to figure out a way to shoehorn the latter into `annotate_snippets`'s data model.

**Comment by ubiratansoares** [comment]
Hey @woodruffw ! I was exploring how we could achieve something around this, how about using [Message::footer](https://docs.rs/annotate-snippets/latest/annotate_snippets/struct.Message.html#method.footer)?

I gave a small try on it, and I've managed to get something like

```text

$> cargo run -- tests/test-data/artipacked.yml

🌈 completed artipacked.yml
warning[artipacked]: credential persistence through GitHub Actions artifacts
  --> tests/test-data/artipacked.yml:13:9
   |
13 |       - uses: actions/checkout@v4
   |         ------------------------- does not set persist-credentials: false
   |
   = note: audit confidence → Low
```

We can customize what we have in the footer message, including colors and etc (no strong opinion here).

**Comment by woodruffw** [comment]
> We can customize what we have in the footer message, including colors and etc (no strong opinion here).

Nice, that looks great! Thanks for looking into it; send a PR and I'll do a full review 🙂

**Comment by woodruffw** [comment]
Closing for now; we can iterate on the display in a follow-up.
