### ISSUE TITLE
Feature: Support cargo binstall

### ISSUE THREAD

**Issue by PolpOnline** [woodruffw/zizmor#215]
### Pre-submission checks

- [X] I am **not** reporting a bug (crash, false positive/negative, etc). These must be filed via the bug report template.
- [X] I have looked through the open issues for a duplicate request.

### What's the problem this feature will solve?

This package does not support [`cargo-binstall`](https://github.com/cargo-bins/cargo-binstall) (no binaries are published with releases)

### Describe the solution you'd like

[`cargo-dist`](https://github.com/axodotdev/cargo-dist) is a nice solution

**Comment by woodruffw** [comment]
Hi @PolpOnline, thanks for the issue! This is being tracked with #169.

Dupes: #210.
