### ISSUE TITLE
[BUG]: Can't use with pre-commit.ci or Ubuntu 24.04 (without updating Rust)

### ISSUE THREAD

**Issue by larsoner** [woodruffw/zizmor#236]
### Pre-submission checks

- [X] I am **not** filing a feature request. These should be filed via the feature request form instead.
- [X] I have looked through the [open issues](https://github.com/woodruffw/zizmor/issues?q=is%3Aissue+is%3Aopen+) for a duplicate report.

### Expected behavior

I expected adding this to `.pre-commit-config.yaml` would work with pre-commit.ci:
```
  - repo: https://github.com/woodruffw/zizmor
    rev: v0.7.0
    hooks:
      - id: zizmor
```

### Actual behavior

Locally on Ubuntu 24.04, my rust was out of date, which was okay to update (but would be a pain to request of devs I work with!). Perhaps more importantly, pre-commit.ci [does not work](https://results.pre-commit.ci/run/github/1301584/1733504387.aVu79oc6Q7Kz2b1Q2GPOww):
```
        Caused by:
          package `zizmor v0.7.0 (/pc/clone/KGSeEdKzTUSVvkVmQjrl4g)` cannot be built because it requires rustc 1.80.1 or newer, while the currently active rustc version is 1.77.0
    Check the log at /pc/pre-commit.log
```

### Reproduction steps

1. Use suggested pre-commit config
2. Enable pre-commit.ci (or just use Ubuntu 24.10 with default rust, etc.)
3. Try to `pre-commit run --all`

### Additional context

Any way the Rust requirement could be lowered? For example for Ubuntu 24.04 LTS has 1.75.

**Comment by woodruffw** [comment]
Thanks for the report @larsoner! Yeah, I think lowering the MSRV to 1.75 should be doable. I'll look into this later today.

**Comment by woodruffw** [comment]
FYI @larsoner: I'm still going to downgrade the MSRV here, but in the mean time `zizmor` is also available on PyPI now, as a precompiled binary for a bunch of different platforms: <https://woodruffw.github.io/zizmor/installation/#pypi>

Hopefully this helps with the pre-commit use case 🙂 -- I'm not super familiar with pre-commit so let me know if there's any upstream repo changes I can/should make to help out as well.

**Comment by graingert** [comment]
ah yes, please could you provide another repo, known as a pre-commit hook mirror, based on https://github.com/astral-sh/ruff-pre-commit/ ?

**Comment by graingert** [comment]
I've had a go here: https://github.com/graingert/zizmor-pre-commit (note the workflow has not been verified by zizmor)

**Comment by graingert** [comment]
note to test out the repo you'll need to do this:

```yaml
repos:
- repo: https://github.com/graingert/zizmor-pre-commit
  # Zizmor version.
  rev: v0.8.0
  hooks:
    # Run the linter.
    - id: zizmor
```

the docs are currently set assuming @woodruffw accepts the transfer

**Comment by woodruffw** [comment]
Thanks @graingert! I've accepted your invite to the repo, but it looks like the transfer might have expired. Could you try doing it again?

> I've requested transfer of the repo to you - I don't know what the security considerations of doing a repo transfer with github actions is!

Me neither, but I trust you :-)

**Comment by graingert** [comment]
Looks like the transfer is still pending:

![Screenshot_20241208-012012](https://github.com/user-attachments/assets/9d28b6ba-343a-4c02-adc8-81ffaea42865)

**Comment by woodruffw** [comment]
Ah, I see it now -- I missed it when I saw the email inviting me to the repo originally. Transfered.

**Comment by woodruffw** [comment]
#247 updates the pre-commit docs.

**Comment by woodruffw** [comment]
@larsoner #249 contains the MSRV drop -- the change in zizmor itself is easy enough, but we have some (test-only, thankfully) deps that require a newer MSRV.

How much would it affect your use case to have the MSRV only apply to the build, and not to the test suite? If that's OK then I can drop the MSRV as-is; if you need the tests as well then I'll need to look a bit further into the deps that are causing issues.

**Comment by graingert** [comment]
I've now tested the new zizmor-pre-commit with pre-commit.ci and it works: https://results.pre-commit.ci/run/github/89922502/1733639851.zfXK9EbiSyWVAl9yW9DFjw

**Comment by larsoner** [comment]
Awesome that it uses pip now, thanks for the very quick response and fix to the pre commit hook!

**Comment by larsoner** [comment]
... And for the MSRV drop I am not very informed but I would say it's okay to have a higher requirement for devs and testing (though it might make Linux packaging people's lives harder at some point!).
