### ISSUE TITLE
Feature: add an audit rule for using actions that include themselves unpinned dependencies

### ISSUE THREAD

**Issue by netomi** [woodruffw/zizmor#253]
### Pre-submission checks

- [X] I am **not** reporting a bug (crash, false positive/negative, etc). These must be filed via the bug report template.
- [X] I have looked through the open issues for a duplicate request.

### What's the problem this feature will solve?

So its not easy to figure out yourself if the action you are using uses itself some transitive dependencies.
For that reason we worked on a tool that allows you to audit actions easily: https://github.com/eclipse-csi/octopin

### Describe the solution you'd like

It would be great if there would be a similar audit rule in zizmor that would indicate if some of the actions uses unpinned dependencies itself. There is no easy fix for that ofc, but at least you know and probably can remove or replace that action in your workflow.

**Comment by woodruffw** [comment]
Thanks for the issue @netomi!

Correct me if I'm wrong, but I think this request is for a composition of two separate features: composite action auditing (which is tracked in https://github.com/woodruffw/zizmor/issues/173) and the `unpinned-uses` audit (which is already implemented).

Given that, I'm inclined to track this with #173 -- once composite actions are supported more generally, it'll be trivial to lift existing audits like `unpinned-uses` onto them.

**Comment by netomi** [comment]
I did not make the connection to #173 but it makes sense to track it in this issue.
There are cases where there is a further traversal, e.g. composite action -> local action -> docker ....

One example is the slsa generic generator workflows, but there might be other cases as well. Feel free organize as needed.

**Comment by woodruffw** [comment]
> There are cases where there is a further traversal, e.g. composite action -> local action -> docker ....

Yeah, long term the plan is to be fully general here: if the user passes a `--recurse` or similar flag, `zizmor` will walk the actions/workflows until it visits all of them.

I'll track this with #173.
