### ISSUE TITLE
Trophy case should accept individual commit links

### ISSUE THREAD

**Issue by girlbossceo** [woodruffw/zizmor#302]
Hi! I came across zizmor when I heard about Ultralytics, and I used zizmor on my [repo](https://github.com/girlbossceo/conduwuit) with 573 stars, and I would like to add it to the trophy case but it only supports PR links where as I typically do a lot of work in one PR and merge it (we're a fast-moving project).

Is it possible for the trophy case to support adding a commit link like this?

https://github.com/girlbossceo/conduwuit/pull/636/commits/c6bf8f5ea15a6b963220a1de4bb50a639d0d0696

**Comment by woodruffw** [comment]
Thanks @girlbossceo! I haven't tested it, but I suspect that kind of direct commit slug should also work and I'd be happy to include it! Please send a PR if you have time; otherwise I can mess around with it later today 🙂

**Comment by girlbossceo** [comment]
It looks like it just gets skipped over by `render-trophies.py` no matter which way I put it.

Adding this in trophies.txt: `girlbossceo/conduwuit/commit/c6bf8f5ea15a6b963220a1de4bb50a639d0d0696`
Outputs:
```
❯ make trophies
make: Nothing to be done for `trophies'.
```

Adding the full URL outputs:
```
uv run --no-project docs/snippets/render-trophies.py > docs/snippets/trophies.md
Traceback (most recent call last):
  File "/Users/strawberry/zizmor/docs/snippets/render-trophies.py", line 23, in <module>
    org, rest = trophy.split("/")
    ^^^^^^^^^
ValueError: too many values to unpack (expected 2)
make: *** [docs/snippets/trophies.md] Error 1
```

**Comment by woodruffw** [comment]
Whoops, that's my bad! I've tweaked the trophy generation and added your project here #303. Thanks for bringing this to my attention!
