### ISSUE TITLE
cache-poisoning: follow-up improvements

### ISSUE THREAD

**Issue by woodruffw** [woodruffw/zizmor#334]
- [x] Evaluate the presence of well-know publish-like Actions (e.g. `gh-action-pypi-publish`) in addition to the trigger-based evaluation #338 
- [ ] Improve evaluation for `push` trigger with well-know branch paths (eg, `release-*` branches) ?
- [x] Add more Actions in the list of well-know cache-aware Actions 😄

_Originally posted by @ubiratansoares in https://github.com/woodruffw/zizmor/issues/294#issuecomment-2547938847_

**Comment by ubiratansoares** [comment]
Investigating some cache-aware Actions I learned that [Mozilla-Actions/sccache-action](https://github.com/Mozilla-Actions/sccache-action) is an example of an Action that has no opt-in/opt-out controls and always cache/restores by default.

We may have more of these, which means that some tweaking on `CacheAwareAction` is needed to reflect the absence of control input / control values

**Comment by ubiratansoares** [comment]
@woodruffw When implementating #345 I found (or remembered?) an interesting thing : it seems that Github URLs actually are not case-senstive. 👀

There are plenty issues / discussions / SO posts [like this one](https://github.com/github/docs/issues/32838), and eventually it's quite easy to check that too: for example, these HTTP GETs download the same tarball ([actions/upload-artifact](https:/github.com/repos/actions/upload-artifact)):

- https://api.github.com/repos/actions/upload-artifact/tarball/6f51ac03b9356f520e9adb1b1b7802705f340c2b
- https://api.github.com/repos/Actions/upload-artifact/tarball/6f51ac03b9356f520e9adb1b1b7802705f340c2b
- https://api.github.com/repos/actions/Upload-Artifact/tarball/6f51ac03b9356f520e9adb1b1b7802705f340c2b

and the same is also true for repositories : 

- https://github.com/PyO3/maturin-action
- https://github.com/pyo3/maturin-action

The issue that follows is that docs like the ones we have for [Mozilla-Actions/sccache-action](https://github.com/Mozilla-Actions/sccache-action) may promote the lowercase template of an Action as provided examples; those surely will be copied and pasted to Workflows in the wild, and the current implementation of `RepositoryUses::matches`  won't be able to match those templates.
 
Ofc this affects mostly `cache-poisoning` for now, but I _think_ the issue happens to all use-cases in which we need to match an Action template. 

The fix should be as simple as matching the lowercase version of each `RepositoryUses` field. Happy to raise a PR as part part of the follow-ups for `cache-poisoning` 🙂

**Comment by woodruffw** [comment]
Good catch! Normalizing to lowercase works fine for me, or doing a case insensitive comparison -- no strong opinions either way.
