### ISSUE TITLE
Docs: document adding or modifying an audit

### ISSUE THREAD

**Issue by woodruffw** [woodruffw/zizmor#46]
This probably belongs in `DEVELOPMENT.md`.

**Comment by ubiratansoares** [comment]
Hey @woodruffw , after working with `insecure-commands` I felt confident to contribute with a proposal here. 

I have a draft on [this branch](https://github.com/woodruffw/zizmor/compare/main...ubiratansoares:zizmor:ufs/patch-05?expand=1). Ofc I did not cover the whole implementation surface, but hopefully those instructions are a good place to start. 

Let me know your thoughts, happy to get input on anything you think is important to have. Happy raise the PR if that already looks good for you 🙂

**Comment by woodruffw** [comment]
> Let me know your thoughts, happy to get input on anything you think is important to have. Happy raise the PR if that already looks good for you 🙂

Thanks @ubiratansoares, that looks like a great start to me! Go ahead and open the PR and I'll do a more in-depth review.
