### ISSUE TITLE
Docs: add requirements to each audit's docs

### ISSUE THREAD

**Issue by woodruffw** [woodruffw/zizmor#47]
Each audit's docs should probably list the audit's requirements, e.g. whether it needs to be online, whether it needs a GitHub API token, etc.

Following #45.

**Comment by ubiratansoares** [comment]
Hey @woodruffw, can I work on this one? 

If yes, my take would be adding something like this on each audit, wtdy? Would I miss something?

```markdown
### Execution requirements

| Description         | Required |
|---------------------|----------|
| Internet connection | No       |
| Github API token    | No       |
| Pedantic mode       | No       |
```

**Comment by woodruffw** [comment]
> Hey @woodruffw, can I work on this one?

Please do, thanks!

> If yes, my take would be adding something like this on each audit, wtdy? Would I miss something?

That looks good, although could I suggest working it into the existing table for each audit rule instead? For example, this could be `impostor-commit`:

| Type | Examples | Introduced in | Works offline? | Enabled by default? |
| ---- | -------- | ------------- | ------- | -------- |
| Workflow | [impostor-commit.yml] | v0.1.0 | ❌ (requires GitHub API token) | ✅ |

...and then we could have a "legend" section at the top explaining that "enabled by default" means it doesn't require `--pedantic` 🙂 

Thoughts? I'm not completely fixed on that, but I think something like that will be easier for people to visually scan.

**Comment by ubiratansoares** [comment]
Your suggestion works for me! Working on that, PR to come!
