### ISSUE TITLE
Complains incorrectly about persist-credentials

### ISSUE THREAD

**Issue by nedbat** [woodruffw/zizmor#51]
zizmor looks great, thanks!  I ran it, it said I should use `persist-credentials: false` for actions/checkout.  I read about it, and added it to all my actions.  Running zizmor again still shows all the same warnings:
```
warning[artipacked]: credential persistence through GitHub Actions artifacts
   --> /Users/ned/coverage/trunk/.github/workflows/kit.yml:149:9
    |
149 |         - name: "Check out the repo"
    |  _________-
150 | |         uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
151 | |         persist-credentials: false
    | |__________________________________- does not set persist-credentials: false
    |
```

What am I doing wrong?  The setting is clearly displayed in the warning output.

**Comment by woodruffw** [comment]
Thanks for trying it out @nedbat!

I think your workflow syntax is wrong, which is why it's not noticing the change: it should be:

```yaml
uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 with:
  persist-credentials: false
```

i.e., you need the `with:` clause.

**Comment by woodruffw** [comment]
(This is a good reminder that I should add warnings when the workflow itself has invalid keys, though!)

**Comment by nedbat** [comment]
My bad, I see the syntax now.  Thanks for the quick response!

**Comment by woodruffw** [comment]
No problem, thanks for confirming! I'll file a follow-up for making it more clear when the workflow itself isn't the shape GHA expects :slightly_smiling_face:

**Comment by gsong** [comment]
I currently use https://github.com/mpalmer/action-validator for this purpose and combine it with zizmor.
