### ISSUE TITLE
Testing: add known-output tests

### ISSUE THREAD

**Issue by woodruffw** [woodruffw/zizmor#55]
The diagnostic-style output isn't stable, but the JSON output is stable enough. So we should have tests that confirm that it doesn't diverge except for when expected (e.g. on new audits/behavioral changes).

**Comment by ubiratansoares** [comment]
Hi @woodruffw ! Thank you so much for creating this project! 

I learned about it today and as a long-term GHA user, I'm super happy that finally we have something like this 🚀

I'd be more than happy to contribute to this project, and in particular I'd like to take ownership of this issue (if no one else is working on it!)

In particular, I have a proposal here on [this branch from my fork](https://github.com/woodruffw/zizmor/compare/main...ubiratansoares:zizmor:ufs/patch-01?expand=1). Some highlights from it (before creating any PR):

- Hardcoding test data from existing samples (adapted)
- Driving the CLI execution with [assert_cmd](https://docs.rs/assert_cmd/latest/assert_cmd/) (from the same authors of Clap)
- Driving assertions over expected output with [serde_json_path](https://docs.rs/serde_json_path/latest/serde_json_path/)
 
Let me know your thoughts 🙂

**Comment by woodruffw** [comment]
Hey @ubiratansoares! Thanks a ton for the kind words, and for volunteering to tackle this!

Your approach looks fantastic -- please go ahead and open a PR and I'll do an in depth review ASAP!
