### ISSUE TITLE
GHA security report cannot show preview

### ISSUE THREAD

**Issue by colindean** [woodruffw/zizmor#57]
I've added a workflow for zizmor in https://github.com/colindean/keepachangelog-parser-java/pull/34. The scanning result in https://github.com/colindean/keepachangelog-parser-java/security/code-scanning/1 shows a file:line coordinate of `gradle.yml:29` but that doesn't exist… it should be `.github/workflows/gradle.yml:29`.

It appears that zizmor is correctly detecting workflows in `.github/workflows` but upon emitting SARIF, the path isn't included.

**Comment by colindean** [comment]
I see the path is available here:

https://github.com/woodruffw/zizmor/blob/8f286b55b5aa683f6d5bd34d05782b7c15b0189f/src/models.rs#L11-L12

I think the trouble begins here where the path gets dropped to get the filename:

https://github.com/woodruffw/zizmor/blob/8f286b55b5aa683f6d5bd34d05782b7c15b0189f/src/models.rs#L45-L49

because the SymbolicLocation loses the path here upon creation:

https://github.com/woodruffw/zizmor/blob/8f286b55b5aa683f6d5bd34d05782b7c15b0189f/src/models.rs#L51-L53

And only the filename gets passed in the SARIF creation:

https://github.com/woodruffw/zizmor/blob/8f286b55b5aa683f6d5bd34d05782b7c15b0189f/src/sarif.rs#L64-L68

Unless this `uri_base_id` is supposed to set a base path that's not working?

https://github.com/woodruffw/zizmor/blob/8f286b55b5aa683f6d5bd34d05782b7c15b0189f/src/sarif.rs#L69

**Comment by woodruffw** [comment]
Thanks for the report @colindean! Yeah, the issue here is that I added a base ID but didn't actually resolve it to anything. I need to look at what other SARIF-emitting tools do to specify a path relative to the "repo root."

**Comment by woodruffw** [comment]
Looked into this a bit: in practice it looks like ~nothing supports `uriBaseId` anyways, and everything just assumes that all results are relative to the working directory. So really what I need to do here is just remove that feature and have everything be relative to the repo root.

**Comment by woodruffw** [comment]
It works!

![](https://thing-in-itself.net/u/K7-DMEW3HSg.png)
