### ISSUE TITLE
Add option to only show findings at given level

### ISSUE THREAD

**Issue by hugovk** [woodruffw/zizmor#60]
When running this on a project with lots of warnings, it would be nice to be able to filter to only show findings at a given level, to be able to tackle the most important ones first.

For example, maybe something like:

```sh
zizmor . --findings high
zizmor . --findings high,medium
zizmor . --findings low,informational
```

**Comment by woodruffw** [comment]
I've recently merged some abstractions that should unblock this: we now have a `FindingRegistry` that allows findings to be filtered as they stream in, so it'd be easy to add some CLI flags to allow severity/confidence filtering.

**Comment by woodruffw** [comment]
#193 does this!

**Comment by hugovk** [comment]
Thank you!
