### ISSUE TITLE
Output: evaluate `codespan` as an alternative to `annotate-snippets`

### ISSUE THREAD

**Issue by woodruffw** [woodruffw/zizmor#63]
Right now we use `annotate-snippets` to provide the default diagnostic output. This works well, but it's a little bit inflexible. We should evaluate [`codespan-reporting`](https://github.com/brendanzab/codespan) as a potential alternative with a more flexible data model.

**Comment by woodruffw** [comment]
Closing for now -- `annotate-snippets` hasn't really caused any issues.

**Comment by epage** [comment]
Feel free to let us know what flexibility issues you run into!

Granted, I think this was opened before 0.12 which is I think when we made things a lot more flexible (enough that it is now used in rustc)

**Comment by woodruffw** [comment]
Thank you! annotate-snippets has honestly been excellent, thanks a ton for the work you've put into it!
