### ISSUE TITLE
Audit documentation should show Bad and Good examples

### ISSUE THREAD

**Issue by miketheman** [woodruffw/zizmor#73]
Many lint tools provide examples of good/bad implementations.

Example:
- https://stylelint.io/user-guide/rules/at-rule-allowed-list
  stylelint uses red/green to show the right/wrong way to do something
- https://eslint.org/docs/latest/rules/constructor-super
  eslint uses icons overload code blocks

The [audit docs](https://github.com/woodruffw/zizmor/tree/main/docs/audit) should include examples to help readers understand the corrective actions.

Related to #48

**Comment by woodruffw** [comment]
This is now done with the "remediation" section in most of the per-audit docs!
