### ISSUE TITLE
Site enhancement ideas

### ISSUE THREAD

**Issue by woodruffw** [woodruffw/zizmor#79]
Opening this to track improvements after the MVP site is done with #78.

- [x] Magic links can be styled with nice little widgets: https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/#repository-link-shortener
- [ ] More GIFs/visual demos?
- [x] Add a logo and favicon
    - [x] #146 
- [ ] Add a testimonials/blog posts section
  * https://nedbatchelder.com/blog/202410/github_action_security_zizmor.html
- [x] Social cards/previews: https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/
- [x] Keep `pre-commit` example updated using a snippet (see #150)

**Comment by woodruffw** [comment]
In terms of "more GIFs": I'd love to use [vhs](https://github.com/charmbracelet/vhs) to automate a bunch of GIF generation, but setting it up both locally and in CI looks like it'll be pretty annoying.

[vhs-action](https://github.com/charmbracelet/vhs-action) might be a part forwards there, although it currently looks like it's geared towards just one demo at a time.

**Comment by cedws** [comment]
I noticed that the icons are missing in the demo GIF currently on main. I was going to open a PR to add a nicer one but creating an issue for this feels silly.

Feel free to use this if you think it's better.

https://github.com/cedws/zizmor/tree/demogif

**Comment by woodruffw** [comment]
Thanks @cedws! IIRC the emojis are missing from the current one because of asciinema; I'm guessing you did this one with vhs?

(I've updated the GIFs.)

**Comment by cedws** [comment]
No problem. Yep used vhs.
