### ISSUE TITLE
Clarify documentation for running inside of GitHub Actions

### ISSUE THREAD

**Issue by danielrbradley** [woodruffw/zizmor#88]
The documentation currently leads with

> zizmor is trivial to use within GitHub Actions; you can run it just like you would locally.

### Clarify cargo usage

How I would run it locally is via `brew`, which doesn't work in GHA so I think this would be better recommending using cargo specifically as I guess that's available in the default image. Also worth noting that cargo might not be a familar tool for many GHA users.

### Inline example

It would be nice to copy the example from your own repository with some brief comments to avoid having to click through to an external repo.

Beyond the example, it would be awesome to have a ready-made action available which hides the cargo and sarif implementation details and allows simple picking of a version to run along with cusomisation of the path. Perhaps this is worth a separate enhancement issue though (https://github.com/woodruffw/zizmor/issues/89)

**Comment by woodruffw** [comment]
Thanks for the report @danielrbradley!

> How I would run it locally is via `brew`, which doesn't work in GHA so I think this would be better recommending using cargo specifically as I guess that's available in the default image. Also worth noting that cargo might not be a familar tool for many GHA users.

FWIW, `brew` does in fact work in GHA, at least for macOS runners -- `brew` should be on the `$PATH`, so `brew install zizmor` will work. But yeah, for other runners, users will (currently) need to do a `cargo install`.


> It would be nice to copy the example from your own repository with some brief comments to avoid having to click through to an external repo.

Makes sense! I would happily review and merge a docs PR that adds the current `zizmor.yml` workflow in this repo to the docs themselves.

For context, https://github.com/woodruffw/zizmor/issues/69 is an earlier request for this. I'm going to some cleanup and dedupe the two + sketch out more of what this should probably look like.

**Comment by woodruffw** [comment]
Closing in favor of ongoing design/discussion in #69.
